### ISSUE TITLE
Countdown Design

### ISSUE THREAD

**Issue by doyoon323** [Clean-Code-Team/Invaders#2]
**Background**
 Whenever game is started, countdown number is on the screen for 3 seconds.

**Task**
- [x] Loading box on the screen at the first time
- [x] Loading progress bar beside the loading box
- [x] Invaders animation on the loading box
- [x] Draw "Loading..." string with blink effect 
- [x] Modify Loading string based on the outline
- [ ] Modify Level string to grow and shrink

**Comment by doyoon323** [comment]
Finished.
